//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPLATE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colline
    {
        public colline()
        {
            this.associations = new HashSet<association>();
            this.clients = new HashSet<client>();
        }
    
        public int ID_colline { get; set; }
        public string NOM_colline { get; set; }
        public int ID_zone { get; set; }
    
        public virtual ICollection<association> associations { get; set; }
        public virtual ICollection<client> clients { get; set; }
        public virtual zone zone { get; set; }
    }
}
