//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPLATE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public profile()
        {
            this.utilisateurs = new HashSet<utilisateur>();
        }
    
        public int ID_profile { get; set; }
        public string NOM_profile { get; set; }
    
        public virtual ICollection<utilisateur> utilisateurs { get; set; }
    }
}
