//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPLATE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualite
    {
        public qualite()
        {
            this.historique_prix = new HashSet<historique_prix>();
            this.recoltes = new HashSet<recolte>();
        }
    
        public int ID_qualite { get; set; }
        public string NOM_qualite { get; set; }
    
        public virtual ICollection<historique_prix> historique_prix { get; set; }
        public virtual ICollection<recolte> recoltes { get; set; }
    }
}
