//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEMPLATE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecolteEntities : DbContext
    {
        public RecolteEntities()
            : base("name=RecolteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<association> associations { get; set; }
        public DbSet<client> clients { get; set; }
        public DbSet<colline> collines { get; set; }
        public DbSet<commune> communes { get; set; }
        public DbSet<employe_association> employe_association { get; set; }
        public DbSet<employe_station_lavage> employe_station_lavage { get; set; }
        public DbSet<historique_asscociation> historique_asscociation { get; set; }
        public DbSet<historique_prix> historique_prix { get; set; }
        public DbSet<historique_station> historique_station { get; set; }
        public DbSet<historique_utilisateur> historique_utilisateur { get; set; }
        public DbSet<profile> profiles { get; set; }
        public DbSet<province> provinces { get; set; }
        public DbSet<qualite> qualites { get; set; }
        public DbSet<recolte> recoltes { get; set; }
        public DbSet<station_lavage> station_lavage { get; set; }
        public DbSet<utilisateur> utilisateurs { get; set; }
        public DbSet<zone> zones { get; set; }
    }
}
